apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: argo-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: asia-south1-docker.pkg.dev/jarvisx-048/argocdtest/master:295
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: argo-test
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008
  type: NodePort
